#!/bin/bash
if [ -z "$1" ]; then
        echo usage: compressimg [file]
        echo This tool will apply common image optimization techniques to the given file.
        exit
fi

# get file meta data
MIMETYPE=`file -b --mime-type $1`
ORIGSIZE=`stat -c%s $1`
if [ "$MIMETYPE" == "image/jpeg" ]; then
	jpegoptim -f --strip-all $1 > /dev/null
elif [ "$MIMETYPE" == "image/png" ]; then
	optipng -quiet -force -o7 $1
	advpng -q -z4 $1
	pngcrush -q -rem gAMA -rem alla -rem cHRM -rem iCCP -rem sRGB -rem time $1 $1.tmp
	mv $1.tmp $1
fi

# show final stats

NEWSIZE=`stat -c%s $1`
NEWSIZEREADABLE=`ls -lah $1 | awk '{ print $5}'`
((PERCENTCHANGE=100-(NEWSIZE*100/ORIGSIZE)))

echo $1: compressed to $NEWSIZEREADABLE \($PERCENTCHANGE% saved\)
